{
 "title": "Admissions Webhook Server",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Validation Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(validation_webhook_request_duration_seconds_bucket[5m])) by (le)) *1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(validation_webhook_request_duration_seconds_bucket[5m])) by (le)) *1000",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(validation_webhook_request_duration_seconds_bucket[5m])) by (le))  *1000",
     "legendFormat": "P99"
    },
    {
     "expr": "rate(validation_webhook_request_duration_seconds_sum[5m]) \n/\nrate(validation_webhook_request_duration_seconds_count[5m])  *1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Mutation Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mutation_webhook_request_duration_seconds_bucket[5m])) by (le)) *1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mutation_webhook_request_duration_seconds_bucket[5m])) by (le)) *1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mutation_webhook_request_duration_seconds_bucket[5m])) by (le)) *1000",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(mutation_webhook_request_duration_seconds_sum[5m]) \n/\nrate(mutation_webhook_request_duration_seconds_count[5m]) *1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Number of Validation requests per second over the last 1 minute.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(validation_webhook_endpoint_total[1m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Number of Mutation requests per second over the last 1 minute.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(mutation_webhook_endpoint_total[1m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total Validation Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(validation_webhook_endpoint_total) by (status)",
     "legendFormat": "{{Total_Requests}}"
    }
   ]
  },
  {
   "title": "Total Mutation Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(mutation_webhook_endpoint_total) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}