apiVersion: v1
kind: Service
metadata:
  name: {{ include "admissions-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: {{ .Values.webhookServer.port }}
  selector:
    app: {{ include "admissions-webhook.fullname" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admissions-webhook.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "admissions-webhook.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.webhookServer.metricsPort }}
      targetPort: {{ .Values.webhookServer.metricsPort }}
  selector:
    app: {{ include "admissions-webhook.fullname" . }}