name: Integrate Webhook Server Source Code
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.2

      - name: Static analysis 
        uses: dominikh/staticcheck-action@024238d2898c874f26d723e7d0ff4308c35589a2
        with:
          version: "2025.1.1"

      - name: Run Build
        run: make build
          
      - name: Run Tests
        run: go test ./... -coverprofile=coverage.out

      # TODO: Migrate to managed server
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Build Docker image
        run: |
          docker build -t admission-webhook:ci .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          image-ref: admission-webhook:ci
          format: table

      - name: Generate TLS certs
        run: make certs
      
      - name: Run and health check container
        run: |
          docker run -d --rm \
            -p 8443:443 \
            -v $(pwd)/certs:/app/certs:ro \
            --name admission_webhook_test \
            admission-webhook:ci \
            --tls-cert-file=/app/certs/tls.crt.pem \
            --tls-private-key-file=/app/certs/tls.key.pem \
            --port=443
          
          sleep 15
          
          curl -sk https://localhost:8443/health || exit 1 
          curl -sk http://localhost:2112/metrics || exit 1

# login to docker hub

# push image to dockerhub
