name: Integrate Webhook Server Source Code
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.2

      - name: Static analysis 
        uses: dominikh/staticcheck-action@024238d2898c874f26d723e7d0ff4308c35589a2
        with:
          version: "2025.1.1"

      - name: Run Build
        run: make build
          
      - name: Run Tests
        run: go test ./...

      # TODO: Migrate to managed server
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Build Docker image
        run: |
          docker build -t admission-webhook:latest .

# run security checks

# IF BUILD REASON WAS MERGE TARGETING MAIN: 

# build docker image 

# run security tests on built image

# run container

# test container 

# login to docker hub

# push image to dockerhub
